import type { ParamMatcher } from '@sveltejs/kit';

const pages = [
	'abliefernachweis',
	'apk',
	'barcodescanner',
	'beipacken',
	'cloudloesung',
	'datenschutz',
	'desadv',
	'download',
	'duv',
	'etikettendrucker',
	'f95',
	'faq',
	'frachtkostenmanagement',
	'g10',
	'gefahrgutabwicklung',
	'gelangensnachweis',
	'gutschriftsanzeigeverfahren',
	'hardware',
	'impressum',
	'k04',
	'karriere',
	'lagerbestandsfuehrung',
	'landing1',
	'landing2',
	'landing3',
	'mailbenachrichtigung',
	'onlinesupport',
	'paketinhaltsliste',
	'partner',
	'pruefungustid',
	'rechnungskontrolle',
	'referenzen',
	'sandbox',
	'service',
	'support',
	'termine',
	'u12',
	'ueberuns',
	'verladekontrolle',
	'vka',
	'waagen',
	'warenversand',
	'gelangensbestaetigung',
	'versandsoftware',
	'versandsystem',
	'bilanz-3-jahre-gelangensbestaetigung',
	'logistiksystem-automatisiert-den-versandprozess',
	'logistiksoftware-vom-wareneingang-ueber-die-kommissionierung-bis-zum-warenversand',
	'logistiksystem-automatisiert-den-versandprozess',
	'versandabwicklung-wichtiger-erfolgsfaktor',
	'paketversandsoftware-fuer-effektive-versandabwicklung',
	'dublettenpruefung-fuer-eindeutige-kundendaten',
	'versandkostenberechnung-senkt-kosten',
	'adressqualitaet-steigert-die-kundenzufriedenheit',
	'adresspruefung-spart-zeit-und-kosten',
	'kommissionieren',
	'versandlogistik-info'
];

export const match: ParamMatcher = (param) => {
	return pages.includes(param);
};
